### ISSUE TITLE
Match the GUIDs with the Original Banks

### ISSUE THREAD

**Issue by Raltyro** [Raltyro/Pizza-Tower-fspro-Recreation#5]
This way, you can connect your modified fspro to pizza tower original banks

**Comment by Raltyro** [comment]
@AwfulNasty hey? any chances you might know how to get the GUID's from the pt original banks

**Comment by AwfulNasty** [comment]
> @AwfulNasty hey? any chances you might know how to get the GUID's from the pt original banks

Here are the bank GUIDs:
Master: {E2E87B09-A147-4E4E-8343-EDEBDE2DDF25}
Master.strings: {7AF55BDD-D03C-020C-050A-67152FDED9BD}
music: {35B06948-BD4A-4D0B-A8FF-041A413B53D8}
sfx: {68835125-DAB1-4312-9B5A-D21EE9BDB318}

As for the GUIDs for the events themselves, those might be a bit harder to extract, but might be possible with a bit of tinkering. They're all housed inside of Master.strings packed back to back.

If you're wondering, I'm using a hex editor on the banks themselves to find these.

**Comment by Raltyro** [comment]
Ah, what about the Main Mixer itself? alsoo iirc you can already get the GUID itself by using the fmod api itself, but i'm still not sure

**Comment by SlawekNowy** [comment]
Yup it's possible to get those via the api.

**Comment by SlawekNowy** [comment]
For Master we would need to call GetBus, then on returned bus object call getID.

**Comment by Raltyro** [comment]
Gotcha, tho i kinda have a doubt that it wouldn't work anyway even if it have the same GUIDs and all
From what i see on researching about it, You can make different banks to play if it's on the same project

**Comment by SlawekNowy** [comment]
In theory it would be possible. Darkest Dungeon exposes part of its (ancient) fspro for linking to banks (ver 1.06.07). The only thing needed here would be the matching version of FMOD Studio itself.

https://www.fmod.com/docs/2.02/studio/welcome-to-fmod-studio-new-in-200.html#project-packaging-and-ugc

**Comment by SlawekNowy** [comment]
I would need to load all banks in the dummy app and dump all guids to a file.
[GUIDs.txt](https://github.com/Raltyro/Pizza-Tower-fspro-Recreation/files/11714451/GUIDs.txt)
Attached is GUID export from the Recreation project.

**Comment by Raltyro** [comment]
> In theory it would be possible. Darkest Dungeon exposes part of its (ancient) fspro for linking to banks (ver 1.06.07). The only thing needed here would be the matching version of FMOD Studio itself.
> 
> https://www.fmod.com/docs/2.02/studio/supporting-downloadable-and-user-generated-content.html#ugc
> 
> Meaning as long we match GUIDs and use the same version, we should be good to go...

Well if that's the case, then we need the FMOD Studio version Pizza Tower uses (i'm guessing its somewhere around 2.02.12, the version that comes out the same month PT releases in steam), but it shouldn't even matter right?

**Comment by Raltyro** [comment]
> I would need to load all banks in the dummy app and dump all guids to a file. [GUIDs.txt](https://github.com/Raltyro/Pizza-Tower-fspro-Recreation/files/11714451/GUIDs.txt) Attached is GUID export from the Recreation project. Which means for complete compatibility we would need to dump Bank, Bus, Event, and Parameter GUIDs.

Hey, uh if you don't mind, can you send the source code you use to dump these

**Comment by SlawekNowy** [comment]
> > I would need to load all banks in the dummy app and dump all guids to a file. [GUIDs.txt](https://github.com/Raltyro/Pizza-Tower-fspro-Recreation/files/11714451/GUIDs.txt) Attached is GUID export from the Recreation project. Which means for complete compatibility we would need to dump Bank, Bus, Event, and Parameter GUIDs.
> 
> Hey, uh if you don't mind, can you send the source code you use to dump these

The ID are the same as listed in Your project, so this wouldn't link cleanly. On your open project press File > Export GUIDs.

I have yet to make an application which dumps the GUIDs from banks.

**Comment by SlawekNowy** [comment]
Ok I made dumps. Quite a few events are missing though.
[GUIDs.txt](https://github.com/Raltyro/Pizza-Tower-fspro-Recreation/files/11715334/GUIDs.txt)
[missingGUIDS.txt](https://github.com/Raltyro/Pizza-Tower-fspro-Recreation/files/11715335/missingGUIDS.txt)

**Comment by SlawekNowy** [comment]
Maybe they are internal?

**Comment by SlawekNowy** [comment]
Here's the bins and source code. You have to supply your own copy of FMOD.

https://mega.nz/folder/rZhUhQ7L#H3hpqs5YAn_HQVcVHtPWcw

**Comment by SlawekNowy** [comment]
Wait... I Found a simpler way...

https://www.fmod.com/docs/2.00/api/studio-api-bank.html#studio_bank_getstringcount

**Comment by SlawekNowy** [comment]
Oh yeah, much better.
[GUIDs.txt](https://github.com/Raltyro/Pizza-Tower-fspro-Recreation/files/11715445/GUIDs.txt)

**Comment by SlawekNowy** [comment]
MEGA link has version 2 alongside version 1 now.

**Comment by AwfulNasty** [comment]
> 

Thanks a bunch for all the help, banks now have the correct GUIDs and can load vanilla sfx and music only using modified master and master.strings. Pushing update soon.
