### ISSUE TITLE
Pause music moved to unsupported bank

### ISSUE THREAD

**Issue by AwfulNasty** [Raltyro/Pizza-Tower-fspro-Recreation#6]
I think that adding new banks just makes the project more difficult for beginners to deal with because banks need to be manually added with changes to the create event of obj_fmod in the game's code. 

At the very least the music/pause event should be moved back to the original music bank, not in mod-music.

@Raltyro if you're on Discord, add Garf#8921 if you want to talk about big changes like these and the GUIDs, I tend to be more available there.

**Comment by Raltyro** [comment]
Oh, i intend to make another branch named "mod-template" that should have those changes
i'll revert them once i made the branch
